[theme]
# Dark theme base
base = "dark"

# General colors
textColor = "#e2e8f0"                 # Default text
primaryColor = "#615fff"               # Buttons, sliders, highlights
backgroundColor = "#1d293d"           # Page background
secondaryBackgroundColor = "#0f172b"  # Sidebar background
accentColor1 = "#F4F754" 
accentColor2 = "#CD2C58"

# Widgets
showWidgetBorder = true
borderColor = "#314158"

# Dataframes
dataframeHeaderBackgroundColor = "#1d293d"
dataframeRowOddBackgroundColor = "#1e2a44"
dataframeRowEvenBackgroundColor = "#1b253d"

# Base text
font = "'Space Grotesk':https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap"
baseFontWeight = 300
baseFontSize = 14

# Heading text
headingFont = "Space Grotesk"
headingFontWeights = [300, 400, 400, 300, 300, 300]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]

[server]
headless = true
port = 8501
enableCORS = false
wideMode = true
